import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactMarkdown from 'react-markdown'
import { ListObjectsCommand, GetObjectCommand } from "@aws-sdk/client-s3"; 
import { s3Client } from '../apis/s3Client'

export async function getServerSideProps() {
  let markdownContent;
  
  const bucketParams = {
    Bucket: 'portfolio-page-bucket',
    Key: 'intro-to-git.md',
  };

  const run = async () => {
    try {
      // Create a helper function to convert a ReadableStream to a string.
      const streamToString = (stream) =>
        new Promise((resolve, reject) => {
          const chunks = [];
          stream.on("data", (chunk) => chunks.push(chunk));
          stream.on("error", reject);
          stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
        });
  
      // Get the object} from the Amazon S3 bucket. It is returned as a ReadableStream.
      console.log('before data');
      
      const data = await s3Client.send(new GetObjectCommand(bucketParams));
      console.log('after data');
      
      // console.log('data.Body: ', data.Body)
      // Convert the ReadableStream to a string.
      const bodyContents = await streamToString(data.Body);
      markdownContent = bodyContents
        return bodyContents;
    } catch (err) {
      console.log("Error", err);
    }
  };
  await run();
  
  return {
    props: { markdownContent }
  }
}

const Home: NextPage = (props) => {
  console.log('props: ', props);
  const { markdownContent } = props;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Createss Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ReactMarkdown>
          { markdownContent }
        </ReactMarkdown>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
